### ISSUE TITLE
leoProfanity.check('.') throws an error

### ISSUE THREAD

**Issue by Baraksi** [jojoee/leo-profanity#10]
Usage is probably not likely to happen, but on rare cases when it does, this error might mess with the code flow.

**Comment by jojoee** [comment]
I try to replicate it but everything seems to be ok.
I would help me a lot if we can reproduce it.

Thanks for reporting.

**Comment by Baraksi** [comment]
Forgot to mention that it happens on nodejs.

Try [https://npm.runkit.com/leo-profanity](https://npm.runkit.com/leo-profanity) and add leoProfanity.check('.')
