### ISSUE TITLE
index.spec.js tests not ran

### ISSUE THREAD

**Issue by darwiin** [jojoee/leo-profanity#2]
Hi,

I'm working on a PR to add french dictionary to your module, but can't get the index.spec.js to work. Running npm test only run Utils.spec.js test.

Could you help me ?

**Comment by jojoee** [comment]
Sure @darwiin,
can you commit your code into your branch please, so I can pull and look into it.
You are working on this one https://github.com/darwiin/leo-profanity, right ?

**Comment by darwiin** [comment]
Thanks @jojoee, Unfortunatly I'm not sure I'm able to do that, see my error below when I try to commit:

```
> leo-profanity@0.0.0-development coverage.check /Users/darwiin/Sources/leo-profanity
> nyc check-coverage --statements 90 --branches 80 --functions 100 --lines 100

ERROR: Coverage for lines (70.51%) does not meet global threshold (100%)
ERROR: Coverage for functions (58.82%) does not meet global threshold (100%)
ERROR: Coverage for branches (46.67%) does not meet global threshold (80%)
ERROR: Coverage for statements (69.88%) does not meet global threshold (90%)
```

**Comment by jojoee** [comment]
Oh, it just because test coverage threshold,
for now, you can change this line on `package.json` file.
```
"coverage.check": "nyc check-coverage --statements 90 --branches 80 --functions 100 --lines 100",
```
to something like
```
"coverage.check": "nyc check-coverage --statements 40 --branches 40 --functions 40 --lines 40",
```

**Comment by jojoee** [comment]
Basically, it will not allow you to commit if coverage is not pass that threshold.
Hope, it can help you :)

**Comment by darwiin** [comment]
Thanks.

I have commited in the branch french-dictionary and put my tests in the `Util.spec.js` because when using my own file I had issues running `npm run validate`.

```
/Users/darwiin/Sources/leo-profanity/test/module/french-badwords-list.spec.js
   5:1  error  'describe' is not defined  no-undef
   6:3  error  'before' is not defined    no-undef
  10:3  error  'describe' is not defined  no-undef
  11:5  error  'it' is not defined        no-undef
  16:5  error  'it' is not defined        no-undef
  22:3  error  'describe' is not defined  no-undef
  23:5  error  'it' is not defined        no-undef
  42:3  error  'describe' is not defined  no-undef
  43:5  error  'it' is not defined        no-undef
```

**Comment by jojoee** [comment]
@darwiin you might need to add `/* global describe, before, it */` in the first line of your file
like I did on `https://github.com/jojoee/leo-profanity/blob/master/test/module/Util.spec.js`

**Comment by darwiin** [comment]
That did the trick, but I'm no longer able to run npm run commit to propose my PR.

**Comment by jojoee** [comment]
@darwiin what the error you got now ?

**Comment by darwiin** [comment]
Sorry for bugging @jojoee here's my new error.

```
> leo-profanity@0.0.0-development commit /Users/darwiin/Sources/leo-profanity
> git-cz

/Users/darwiin/Sources/leo-profanity/node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
```

I think it's because I've already commit  without using `npm run commit`

**Comment by jojoee** [comment]
The error happens cause you try to commit without adding any files, try this
1. add file
2. run `npm run commit`

**Comment by darwiin** [comment]
Thanks @jojoee I thought that was the issue. I already have commited my changes without using `npm run commit` I have created my PR.

**Comment by darwiin** [comment]
Many thanks for your help.
