### ISSUE TITLE
How to Handle profanity in Quotes?

### ISSUE THREAD

**Issue by sfi2k7** [jojoee/leo-profanity#23]
It seems our "users" are starting to notice that if they put a quote around a bad word it won't get filtered.
Is there an option to handle those situations?

**Comment by jojoee** [comment]
The original idea of a library is to be a rough filter that provides basic filtering to the language that has space in the grammar e.g. English.

As mentioned in the "Summary" section
```
People will always find a way to connect with each other (e.g. Leet)
```
We knew that we can't completely filter it based on this algorithm.

For this situation that people find a way to trick the filter, which says we always have to catch up with the trick to prevent it. In this case, we are not so sure how to prevent it (if we are able to handle this specific trick we will face this kind of situation in the future).

Lastly, for more advanced techniques I might suggest addressing it with NLP-based technique and keep training the model to the recent one to catch up the temporal effects as well.
