### ISSUE TITLE
Count words filtered

### ISSUE THREAD

**Issue by nseb** [jojoee/leo-profanity#24]
It's possible to have the words was filtered ? 
This makes it possible to know if the text contains vulgar words, to be able to tag the content as with a particular state.

**Comment by jojoee** [comment]
hmm very interesting 🔥
How about adding a new function to return the words that will be filtered ? like the below

```javascript
// output: "I have ****"
filter.clean('I have BoOb');

// new function
// output: "BoOb"
filter.getFilteredWords('I have BoOb');
```

Do you think this method met the requirement? if yes I will add this function and release it in the next version.

**Comment by nseb** [comment]
or method clean , return a object like : 
let result = filter.clean('I have BoOb');
result like this 
{ content : 'I have ****' , 
 countWordFiltered = 1,
 wordFiltered = ['BooB']
}
or promise ?

**Comment by jojoee** [comment]
I try to preserve backward compatibility as much as possible, so I'm thinking about creating another function to avoid breaking the change of the existing implementation.

It will release with the next version of the library.
Thank you so much for the recommendation kub 😄

**Comment by jojoee** [comment]
Due to no response, I'm closing the issue.
Please ping me if any updates to it 🙏
